Szakdolgozat: cpp/gps.hpp File Reference
gps.hpp File Reference
#include <string>
Classes
class GPSDataClass
Functions
GPSDataClass returnGPSData ()
int gpsCom ()
bool gpsInit ()
Variables
GPSDataClass gpsdata
Function Documentation
gpsCom()
int gpsCom ()
A GPS kommunikációért felelős függvény.
Returns
Mindig -1, jelezve, hogy a függvény sosem tér vissza normál módon.
Definition at line 150 of file log.cpp.
References DEBUG, DEBUG_GPS_GPGGA, processGPSData(), serial_port, and tty_old.
Referenced by main().
gpsInit()
bool gpsInit ()
Inicializálja a GPS-t a soros porton keresztül.
Returns
True, ha a GPS inicializálása sikeres, egyébként false.
Definition at line 106 of file log.cpp.
References serial_port, tty, and tty_old.
Referenced by main().
returnGPSData()
GPSDataClass returnGPSData ()
Visszaadja az aktuális GPS adatokat.
Returns
Az aktuális GPS adatokat tartalmazó objektum.
Definition at line 46 of file log.cpp.
References gpsdata, and gpsDataMutex.
Referenced by main().
Variable Documentation
gpsdata
GPSDataClass gpsdata extern
Globális változó a GPS adatok tárolására.
Definition at line 22 of file log.cpp.
Referenced by processGPSData(), and returnGPSData().