MyProject: cpp/log.cpp File Reference
log.cpp File Reference
#include <iostream>
#include <fcntl.h>
#include <termios.h>
#include <unistd.h>
#include <cstring>
#include <stdio.h>
#include <sstream>
#include <string>
#include <vector>
#include <mutex>
#include <thread>
#include <chrono>
#include "gps.hpp"
Macros
#define DEBUG 1
#define DEBUG_GPS_GPGGA 1
Functions
vector< string > split (const string &s, char delimiter)
GPSDataClass returnGPSData ()
void processGPSData (string rawGPSData)
bool gpsInit ()
int gpsCom ()
Variables
mutex gpsDataMutex
GPSDataClass gpsdata
struct termios tty
struct termios tty_old
int serial_port
Macro Definition Documentation
DEBUG
#define DEBUG 1
Hiba kereséshez
Definition at line 15 of file log.cpp.
DEBUG_GPS_GPGGA
#define DEBUG_GPS_GPGGA 1
Ha nincs GPS, akkor 1 értékkel lehet imitálni
Definition at line 16 of file log.cpp.
Function Documentation
gpsCom()
int gpsCom ()
A GPS kommunikáció.
Returns
0 ha minden jó.
Definition at line 150 of file log.cpp.
References DEBUG, DEBUG_GPS_GPGGA, processGPSData(), serial_port, and tty_old.
Referenced by main().
gpsInit()
bool gpsInit ()
Inicializálja a GPS-t a soros porton keresztül.
Returns
True, ha a GPS inicializálása sikeres, egyébként false.
Definition at line 106 of file log.cpp.
References serial_port, tty, and tty_old.
Referenced by main().
processGPSData()
void processGPSData (string rawGPSData)
Feldolgozza a nyers GPS adatokat és frissíti a globális GPS adat változót.
Parameters
rawGPSData A nyers GPS adatok string formátumban.
Definition at line 63 of file log.cpp.
References GPSDataClass::age, GPSDataClass::alt, GPSDataClass::aunits, GPSDataClass::checksum, gpsdata, gpsDataMutex, GPSDataClass::hdop, GPSDataClass::lat, GPSDataClass::lat_dir, GPSDataClass::lon, GPSDataClass::lon_dir, GPSDataClass::quality, GPSDataClass::sats, split(), GPSDataClass::time, GPSDataClass::type, GPSDataClass::undulation, and GPSDataClass::uunits.
Referenced by gpsCom().
returnGPSData()
GPSDataClass returnGPSData ()
Visszaadja az aktuális GPS adatokat.
Returns
Az aktuális GPS adatokat tartalmazó objektum.
Definition at line 46 of file log.cpp.
References gpsdata, and gpsDataMutex.
Referenced by main().
split()
vector< string > split (const string & s, char delimiter)
Egy stringet darabol fel a megadott elválasztó alapján.
Parameters
s A bemeneti string.
delimiter Az elválasztó karakter.
Returns
A darabolt stringek listája.
Definition at line 31 of file log.cpp.
Referenced by processGPSData().
Variable Documentation
gpsdata
GPSDataClass gpsdata
GPS adatok tárolásához.
Definition at line 22 of file log.cpp.
Referenced by processGPSData(), and returnGPSData().
gpsDataMutex
mutex gpsDataMutex
Szálkezeléshez
Definition at line 20 of file log.cpp.
Referenced by processGPSData(), and returnGPSData().
serial_port
int serial_port
Serial port száma
Definition at line 99 of file log.cpp.
Referenced by gpsCom(), and gpsInit().
tty
struct termios tty
Terminal vezérlés
Definition at line 97 of file log.cpp.
Referenced by gpsInit().
tty_old
struct termios tty_old
Terminal vezérlés
Definition at line 98 of file log.cpp.
Referenced by gpsCom(), and gpsInit().