MyProject: cpp/yolo.cpp File Reference
yolo.cpp File Reference
#include <fstream>
#include <iostream>
#include <thread>
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include "gps.hpp"
Classes
struct Detection
Functions
std::vector< std::string > load_class_list ()
void load_net (dnn::Net &net, bool is_cuda)
Mat format_yolov5 (const Mat &source)
void detect (Mat &image, dnn::Net &net, std::vector< Detection > &output, const std::vector< std::string > &className)
int main (int argc, char **argv)
Variables
bool gpsIsConnected
const float INPUT_WIDTH = 640.0
const float INPUT_HEIGHT = 640.0
const float SCORE_THRESHOLD = 0.05
const float NMS_THRESHOLD = 0.1
const float CONFIDENCE_THRESHOLD = 0.06
const std::vector< Scalar > colors = {Scalar(255, 255, 0), Scalar(0, 255, 0), Scalar(0, 255, 255), Scalar(255, 0, 0)}
Function Documentation
detect()
void detect (Mat & image, dnn::Net & net, std::vector< Detection > & output, const std::vector< std::string > & className)
Objektumok detektálása egy képen.
Parameters
image A bemeneti kép.
net neurális háló
output detekt lista
className osztálynevek listája
Definition at line 100 of file yolo.cpp.
References Detection::box, Detection::class_id, Detection::confidence, CONFIDENCE_THRESHOLD, format_yolov5(), INPUT_HEIGHT, INPUT_WIDTH, NMS_THRESHOLD, and SCORE_THRESHOLD.
Referenced by main().
format_yolov5()
Mat format_yolov5 (const Mat & source)
Formázza az input képet a YOLOv5 modell számára.
Parameters
source Az eredeti kép.
Returns
A formázott kép.
Definition at line 83 of file yolo.cpp.
Referenced by detect().
load_class_list()
std::vector< std::string > load_class_list ()
Betölti a classokat, amiket detektálni tudunk.
Returns
A classok neveit tartalmazó string lista.
Definition at line 39 of file yolo.cpp.
Referenced by main().
load_net()
void load_net (dnn::Net & net, bool is_cuda)
Betölti a neurális hálót.
Parameters
net A neurális háló objektuma.
is_cuda Ha igaz, akkor a CUDA magokat használja.
Definition at line 57 of file yolo.cpp.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 165 of file yolo.cpp.
References colors, detect(), gpsCom(), gpsInit(), gpsIsConnected, GPSDataClass::lat, load_class_list(), load_net(), GPSDataClass::lon, returnGPSData(), GPSDataClass::time, and GPSDataClass::type.
Variable Documentation
colors
const std::vector<Scalar> colors = {Scalar(255, 255, 0), Scalar(0, 255, 0), Scalar(0, 255, 255), Scalar(255, 0, 0)}
Definition at line 75 of file yolo.cpp.
Referenced by main().
CONFIDENCE_THRESHOLD
const float CONFIDENCE_THRESHOLD = 0.06
Definition at line 21 of file yolo.cpp.
Referenced by detect().
gpsIsConnected
bool gpsIsConnected
Ha USB csatlakoztatva akkor true.
Definition at line 14 of file yolo.cpp.
Referenced by main().
INPUT_HEIGHT
const float INPUT_HEIGHT = 640.0
Kép csatolva a GitHub repoba
Definition at line 18 of file yolo.cpp.
Referenced by detect().
INPUT_WIDTH
const float INPUT_WIDTH = 640.0
Kép csatolva a GitHub repoba
Definition at line 17 of file yolo.cpp.
Referenced by detect().
NMS_THRESHOLD
const float NMS_THRESHOLD = 0.1
Definition at line 20 of file yolo.cpp.
Referenced by detect().
SCORE_THRESHOLD
const float SCORE_THRESHOLD = 0.05
Definition at line 19 of file yolo.cpp.
Referenced by detect().